parameters:
    env(DATABASE_URL): 'sqlite:///%kernel.project_dir%/var/data/hittracker.db'
    database_url: "%env(DATABASE_URL)%"
    database_driver: 'pdo_sqlite'
    session_handler: session.handler.native_file
    secure_cookies: false

