parameters:
    env(HITTRACKER_DATABASE_HOST): 127.0.0.1
    env(HITTRACKER_DATABASE_PORT): ~
    env(HITTRACKER_DATABASE_NAME): hittracker
    env(HITTRACKER_DATABASE_USER): hittracker
    env(HITTRACKER_DATABASE_PASSWORD): ~

    pubsub_nginx_push_stream_url: "https://ht.local.dev/publish/game"
    livereload_http_url: "https://ht.local.dev/livereload.js?port=443"
    livereload_ws_url: "wss://ht.local.dev"

    database_driver: pdo_pgsql
    database_host: "%env(HITTRACKER_DATABASE_HOST)%"
    database_port: "%env(HITTRACKER_DATABASE_PORT)%"
    database_name: "%env(HITTRACKER_DATABASE_NAME)%"
    database_user: "%env(HITTRACKER_DATABASE_USER)%"
    database_password: "%env(HITTRACKER_DATABASE_PASSWORD)%"
