preset: recommended

disabled:
    - align_double_arrow
    - blankline_after_open_tag
    - phpdoc_params
    - phpdoc_separation
    - phpdoc_short_description
    - phpdoc_to_comment
    - short_array_syntax
    - multiline_array_trailing_comma
    - multiline_spaces_before_semicolon
