preset: recommended

disabled:
    - align_double_arrow
    - phpdoc_params
    - phpdoc_separation
    - phpdoc_short_description
    - phpdoc_to_comment
    - short_array_syntax
    - spaces_before_semicolon
