dist: trusty
sudo: false
language: php

php:
    - 7.1

sudo: false
cache:
    directories:
        - $HOME/.cache/composer

env:
    global:
        - COMPOSER_NO_INTERACTION=1
        - SYMFONY_DEBUG=true
        - SYMFONY_ENV=test
        - SYMFONY__DATABASE_NAME=hittracker
        - SYMFONY__DATABASE_USER=postgres
        - SYMFONY__SECRET=ff3464e484bb524fb4234e893f9cee58
    matrix:
        - SYMFONY__BUILD_TYPE=hosted
        - SYMFONY__BUILD_TYPE=standalone
        - SYMFONY__BUILD_TYPE=electron

services:
  - postgresql
addons:
    postgresql: '9.6'

install:
    - composer install

before_script:
    - php bin/console doctrine:database:create
    - php bin/console doctrine:migrations:migrate
#    - php bin/console doctrine:fixtures:load
    - php bin/console cache:warmup

script:
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v
  - ./vendor/bin/phpstan analyse -l5 src/ -c phpstan.neon
  - ./vendor/bin/phpunit

