language: php

php:
    - 5.6
    - hhvm
    - hhvm-nightly

env:
    global:
        - SYMFONY_DEBUG=1
        - SYMFONY_ENV=dev
        - SYMFONY__DATABASE_NAME=ht
        - SYMFONY__DATABASE_USER=postgres
        - SYMFONY__DATABASE_PASSWORD=""
        - SYMFONY_SECRET=ff3464e484bb524fb4234e893f9cee58

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

# TODO: go back to addons when travis supports pg 9.4
# https://github.com/travis-ci/travis-ci/issues/2983
#addons:
#    postgresql: '9.3'

before_install:
    - sudo apt-get update
    - sudo apt-get purge postgresql-9.1 postgresql-9.2 postgresql-9.3
    - sudo apt-get install postgresql-client-common postgresql-9.4
    - sudo service postgresql start
    - composer self-update
install:
    - composer install --prefer-source --no-interaction

before_script:
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test
#    - php bin/console doctrine:fixtures:load -n --env=test
    - php bin/console cache:warmup --env=test

#script: phpunit --coverage-clover=coverage.clover
#after_script: # for usage with scrutinizer
#    - wget https://scrutinizer-ci.com/ocular.phar
#    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
