language: php

php:
    - 7.0
    - hhvm
    - hhvm-nightly

sudo: false
cache:
    directories:
        - vendor
        - $HOME/.composer/cache
env:
    global:
        - SYMFONY_DEBUG=true
        - SYMFONY_ENV=test
        - SYMFONY__DATABASE_NAME=ht
        - SYMFONY__DATABASE_USER=postgres
        - SYMFONY__SECRET=ff3464e484bb524fb4234e893f9cee58
    matrix:
        - SYMFONY__BUILD_TYPE=hosted
        - SYMFONY__BUILD_TYPE=standalone

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

addons:
    postgresql: '9.4'

before_install:
    - composer self-update
install:
    - composer install --prefer-source --no-interaction

before_script:
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test
#    - php bin/console doctrine:fixtures:load -n --env=test
    - php bin/console cache:warmup --env=test

#script: phpunit --coverage-clover=coverage.clover
#after_script: # for usage with scrutinizer
#    - wget https://scrutinizer-ci.com/ocular.phar
#    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
