dist: trusty
sudo: false
language: php

php:
    - 7.2

sudo: false
cache:
    directories:
        - $HOME/.composer

env:
    global:
        - PGPORT=5433
        - COMPOSER_NO_INTERACTION=1
        - APP_DEBUG=1
        - APP_ENV=test
        - APP_SECRET=ff3464e484bb524fb4234e893f9cee58
    matrix:
        - APP_BUILD_TYPE=hosted
          APP_LOG_DIR="var/logs"
          APP_CACHE_DIR="var/cache"
          DATABASE_URL=pgsql://postgres@localhost/hittracker
        - APP_BUILD_TYPE=appliance
          APP_LOG_DIR="var/logs"
          APP_CACHE_DIR="var/cache"
        - APP_BUILD_TYPE=electron
          APP_VAR_DIR="var"
          DATABASE_URL="sqlite:///var/data/hitttracker.db"

#-services:
#  - postgresql
addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

install:
    - export PHPRC=$TRAVIS_BUILD_DIR/etc/php/$APP_BUILD_TYPE/php-unix-development.ini
    - export PHP_INI_SCAN_DIR=""
    - composer install --prefer-dist --no-suggest

before_script:
    - php bin/console doctrine:database:create
    - php bin/console doctrine:migrations:migrate --no-interaction
#    - php bin/console doctrine:fixtures:load --no-interaction
    - php bin/console cache:warmup

script:
    - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v
    - ./vendor/bin/phpstan analyse --memory-limit="-1" -l7 -c phpstan.neon etc src/ bin/
    - ./vendor/bin/phpunit

before_deploy:
    - php bin/package.php --build-version=$TRAVIS_TAG --build-platform=linux --build-type=$APP_BUILD_TYPE --compress --use-existing-vendor

deploy:
    provider: releases
    api_key:
        secure: "LJ1ZwqBmg6GajDkgtFrgkNttfmBObPAAUPnJr8d53mXEA6+ZwZw/fIXOt7BzOQOow2DWMDf+PAqMkmSQLwdjnRB+jGIa4yJHnOQ1BxgyLuiQ5yiFckkHwBt+1HrKGZ54uxaQBej1/wbBi1GrEhz5BNWjAsHotGVMbiJ6dR4uU24="
    file: "*.tar.bz2"
    file_glob: true
    skip_cleanup: true
    on:
        tags: true

branches:
    except:
        - gh-pages
