build: false
platform:
  - x64
clone_folder: C:\projects\php-project-workspace

environment:
  matrix:
    - php_ver_target: 7.1

cache:
    - '%LOCALAPPDATA%\Composer\files -> composer.lock'
    - composer.phar
    - C:\ProgramData\chocolatey\bin -> .appveyor.yml
    - C:\ProgramData\chocolatey\lib -> .appveyor.yml
    - C:\tools\php -> .appveyor.yml

init:
    - SET PATH=C:\Program Files\OpenSSL;C:\tools\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHPRC=.\etc\php.ini
    - SET PHP_INI_SCAN_DIR=.\etc\php\win32
    - SET SYMFONY__BUILD_TYPE=electron
    - SET SYMFONY_DEBUG=true
    - SET SYMFONY_ENV=test
    - SET PHP=1 # This var is connected to PHP install cache
    - SET ANSICON=121x90 (121x90)

install:
    - IF EXIST c:\tools\php (SET PHP=0)
    - ps: appveyor-retry cinst --params '""/InstallDir:C:\tools\php""' --ignore-checksums -y php --version ((choco search php --exact --all-versions -r | select-string -pattern $env:php_ver_target | sort { [version]($_ -split '\|' | select -last 1) } -Descending | Select-Object -first 1) -replace '[php|]','')
    - cd c:\tools\php
      #- IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
    - cd C:\projects\php-project-workspace
    - appveyor-retry composer install --no-progress --profile
    - bin/console doctrine:database:create
    - bin/console doctrine:migrations:migrate --no-interaction
    - bin/console cache:clear

test_script:
    - cd C:\projects\php-project-workspace
    - vendor/bin/phpunit -c phpunit.xml.dist

branches:
  except:
    - gh-pages


