imports:
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en_US
    icu_time_date_format: 'MM/dd/y hh:mm a'
    upload_files_dir: '%kernel.root_dir%/../web/uploads'
    upload_uri_base_prefix: '/uploads'

framework:
    translator:
        fallback: "%locale%"
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    serializer:
        enable_annotations: true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  "%session_handler%"
        cookie_secure: "%session_cookie_secure%"
    fragments:       ~
    http_method_override: true
    assets:
        #version: SomeVersionScheme
    php_errors:
        log: true

twig:
    form_themes:
        - bootstrap_3_horizontal_layout.html.twig
        - '@Common/form_theme.html.twig'
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        livereload_script_url: "%livereload_http_url%"
        icu_time_date_format: "%icu_time_date_format%"

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        path:     "%database_path%"
        charset:  UTF8
        TODO: remove this when doctrine fixes server_version detection
        server_version: "%database_server_version%"
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
                LazerBall\HitTracker\Model:
                    type: annotation
                    dir: '%kernel.root_dir%/../src/Model'
                    is_bundle: false
                    prefix: LazerBall\HitTracker\Model
                    alias: HitTracker

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../migrations"
    namespace: "LazerBall\\HitTracker\\Migrations"

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    request:
        converters: true
    view:
        annotations: true
    router:
        annotations: true

fos_rest:
    #disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    view:
        mime_types:
            json:
                - 'application/json'
                - 'application/json;version=0.1'
        view_response_listener: 'force'
        formats:
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - path: ^/
              priorities: [html, json]
              fallback_format: html
    versioning:
        enabled: true
        resolvers:
            media_type:
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'

    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true

c33s_static_page_content:
    content_bundle: HitTrackerGameBundle
    content_dir: Pages

sylius_settings:
    driver: doctrine/orm

doctrine_cache:
    providers:
        sylius_settings:
            type: file_system

sylius_resource:
    resources:
        hittracker.vest:
            templates: "@HitTrackerGame/Vest"
            classes:
                model: LazerBall\HitTracker\Model\Vest
                repository: LazerBall\HitTracker\GameBundle\Entity\VestRepository
                form: LazerBall\HitTracker\GameBundle\Form\Type\VestType

        hittracker.game:
            templates: "@HitTrackerGame/Game"
            classes:
                model: LazerBall\HitTracker\Model\Game
                controller: LazerBall\HitTracker\GameBundle\Controller\GameController
                repository: LazerBall\HitTracker\GameBundle\Entity\GameRepository
                form: LazerBall\HitTracker\GameBundle\Form\Type\GameType

nelmio_security:
    signed_cookie:
        names: ['*']
    clickjacking:
        paths:
            '^/games/active': SAMEORIGIN
            '^/games/scorecard': SAMEORIGIN
            '^/.*': DENY
    external_redirects:
        abort: true
        log: true
    #csp:
    #    report_logger_service: monolog.logger.security
    #    report:
    #        report-uri: [/csp/report]
    #        default-src: [ 'self' ]
    #        img-src:
    #            - 'data:'
    #            - 'self'
    #        object-src:
    #            - 'none'
    #        style-src:
    #            - 'unsafe-inline'
    #            - 'self'
    #        frame-src:
    #            - 'blackfire.io'
    #            - 'self'
    #    enforce:
    #        report-uri: [/csp/report]
    #        script-src:
    #            - 'self'
    content_type:
        nosniff: true
    forced_ssl:
        enabled: "%hsts_enabled%"
        hsts_max_age: 10886400
        hsts_subdomains: false
        hsts_preload: true

hittracker_game:
    event_handlers:
        nginx_push_stream:
            url: "%nginx_push_stream_url%"
