#imports:
#    - { resource: security.yml }

framework:
    translator:
        fallback: en
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines: ['twig']
    default_locale:  en
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.pdo
        cookie_httponly: true
        cookie_secure: true
    fragments:       ~
    http_method_override: true

twig:
    #form_themes:
    #    - bootstrap_3_horizontal_layout.html.twig
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # TODO: remove this when doctrine fixes server_version detection
        server_version: 9.4
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    request:
        converters: true
    view:
        annotations: false
    router:
        annotations: true

fos_rest:
    #disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    view:
        mime_types:
            json:
                - 'application/json'
                - 'application/json;version=0.1'
        view_response_listener: 'force'
        formats:
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - path: ^/
              priorities: [html, json]
              fallback_format: html
        media_type:
            version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true

c33s_static_page_content:
    content_bundle: HitTrackerGameBundle
    content_dir: Pages

sylius_settings:
    driver: doctrine/orm

doctrine_cache:
    providers:
        sylius_settings:
            type: file_system

sylius_resource:
    resources:
        hittracker.vest:
            driver: doctrine/orm
            templates: HitTrackerGameBundle:Vest
            classes:
                model: LazerBall\HitTracker\GameBundle\Entity\Vest
                #interface: App\Entity\UserInterface
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: LazerBall\HitTracker\GameBundle\Entity\VestRepository
        hittracker.game:
            driver: doctrine/orm
            templates: HitTrackerGameBundle:Game
            classes:
                model: LazerBall\HitTracker\GameBundle\Entity\Game
                #interface: App\Entity\UserInterface
                controller: LazerBall\HitTracker\GameBundle\Controller\GameController
                repository: LazerBall\HitTracker\GameBundle\Entity\GameRepository

nelmio_security:
    signed_cookie:
        names: ['*']
    encrypted_cookie:
        names: ['*']
    clickjacking:
        paths:
            '^/games/active': SAMEORIGIN
            '^/games/scorecard': SAMEORIGIN
            '^/.*': DENY
    external_redirects:
        abort: true
        log: true
    csp:
        report_logger_service: monolog.logger.security
        report:
            report-uri: [/csp/report]
            default-src: [ 'self' ]
            img-src:
                - 'data:'
                - 'self'
            object-src:
                - 'none'
            style-src:
                - 'unsafe-inline'
                - 'self'
        enforce:
            report-uri: [/csp/report]
            script-src:
                - 'self'
    content_type:
        nosniff: true
    forced_ssl:
        enabled: true
        hsts_max_age: 10886400
        hsts_subdomains: false
        hsts_preload: true

hittracker_game:
    event_handlers:
        nginx_push_stream:
            url: "https://ht.local.dev/publish/game"
