framework:
    session:
        cookie_secure: false

hittracker_game:
    event_handlers:
        nginx_push_stream:
            url: "http://localhost/publish/game"

nelmio_security:
    forced_ssl: false
