imports:
    - { resource: parameters.default.yml }
#    - { resource: security.yml }

framework:
    #esi: ~
    translator:
        fallback: "%locale%"
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
        api: 2.5-bc
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        cookie_httponly: true
        #cookie_secure: true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    request:
        converters: true
    view:
        annotations: true
    router:
        annotations: true

c33s_static_page_content:
    content_bundle: HitTrackerGameBundle
    content_dir: Pages

sylius_settings:
    driver: doctrine/orm

doctrine_cache:
    providers:
        sylius_settings:
            type: file_system

sylius_resource:
    resources:
        hittracker.vest:
            driver: doctrine/orm
            templates: HitTrackerGameBundle:Vest
            classes:
                model: HitTracker\GameBundle\Entity\Vest
                #interface: App\Entity\UserInterface
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: HitTracker\GameBundle\Entity\VestRepository
        hittracker.game:
            driver: doctrine/orm
            templates: HitTrackerGameBundle:Game
            classes:
                model: HitTracker\GameBundle\Entity\Game
                #interface: App\Entity\UserInterface
                controller: HitTracker\GameBundle\Controller\GameController
                repository: HitTracker\GameBundle\Entity\GameRepository
