parameters:
    database_host: ~
    database_port: ~
    database_path: ~
    database_password: ~

    livereload_http_url: "http://localhost/livereload.js"
    livereload_ws_url: "ws://localhost"

    pubsub_nginx_push_stream_url: ~
    pubsub_apcu_cache_key: ~

    mailer_transport: ~
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~

