parameters:
    database_host: 127.0.0.1
    database_port: ~
    database_name: ht
    database_user: postgres
    database_password: ~

    mailer_transport: ~
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~

    # TODO: remove me when https://github.com/Sylius/Sylius/issues/2705 is fixed
    sylius.cache:
        type: file_system

