parameters:
    database_name:     ht_prod
    database_user:     ht
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    secret:            ThisTokenIsNotSoSecretChangeIt

    debug_toolbar:          true
    debug_redirects:        false
