page:
    path:  /pages/{name}
    defaults:
        _controller: "C33sStaticPageContentBundle:BaseStaticPage:show"
home:
    path: /
    defaults:
        _controller: "C33sStaticPageContentBundle:BaseStaticPage:show"
        name: help
