hittracker_game:
    resource: "@HitTrackerGameBundle/Resources/config/routing.yml"

sylius_settings:
    path: /settings
    defaults:
        _controller: sylius.controller.settings:updateAction
        template: SyliusSettingsBundle:Settings:update.html.twig
        namespace: game

page:
    path:  /pages/{name}
    defaults:
        _controller: "C33sStaticPageContentBundle:BaseStaticPage:show"
home:
    path: /
    defaults:
        _controller: "C33sStaticPageContentBundle:BaseStaticPage:show"
        name: help
