framework:
    session:
        handler_id: session.handler.native_file
        cookie_secure: false

doctrine:
    dbal:
        driver: pdo_sqlite
        path: "%database_path%"

hittracker_pubsub:
    handlers:
        apcu:
            cache_key: "hittracker.events"
