<?php declare(strict_types=1);

return [
    \Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => [],
    \Symfony\Bundle\SecurityBundle\SecurityBundle::class => [],
    \Symfony\Bundle\TwigBundle\TwigBundle::class => [],
    \Symfony\Bundle\MonologBundle\MonologBundle::class => [],
    \Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => [],
    \Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => [],
    \WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle::class => [],
    \winzou\Bundle\StateMachineBundle\winzouStateMachineBundle::class => [],
    \Sylius\Bundle\UiBundle\SyliusUiBundle::class => [],
    \Sylius\Bundle\ResourceBundle\SyliusResourceBundle::class => [],
    \Sylius\Bundle\SettingsBundle\SyliusSettingsBundle::class => [],
    \Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => [],
    \Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => [],
    \FOS\RestBundle\FOSRestBundle::class => [],
    \JMS\SerializerBundle\JMSSerializerBundle::class => [],
    \LazerBall\HitTracker\PubSubBundle\PubSubBundle::class => [],
    \LazerBall\HitTracker\GameBundle\HitTrackerGameBundle::class => [],
    \C33s\StaticPageContentBundle\C33sStaticPageContentBundle::class => [],
    \Nelmio\SecurityBundle\NelmioSecurityBundle::class => [],
    \Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => [],
    \Bazinga\Bundle\HateoasBundle\BazingaHateoasBundle::class => [],
    \Dunglas\DoctrineJsonOdm\Bundle\DunglasDoctrineJsonOdmBundle::class => [],
    \Incenteev\HashedAssetBundle\IncenteevHashedAssetBundle::class => [],
    \Symfony\Bundle\DebugBundle\DebugBundle::class => ['development' => true, 'test' => true],
    \Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['development' => true, 'test' => true],
];
