<?php declare(strict_types=1);

return [
    \Symfony\Bundle\FrameworkBundle\FrameworkBundle::CLASS => [],
    \Symfony\Bundle\SecurityBundle\SecurityBundle::CLASS => [],
    \Symfony\Bundle\TwigBundle\TwigBundle::CLASS => [],
    \Symfony\Bundle\MonologBundle\MonologBundle::CLASS => [],
    \Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::CLASS => [],
    \Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::CLASS => [],
    \WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle::CLASS => [],
    \winzou\Bundle\StateMachineBundle\winzouStateMachineBundle::CLASS => [],
    \Sylius\Bundle\UiBundle\SyliusUiBundle::CLASS => [],
    \Sylius\Bundle\ResourceBundle\SyliusResourceBundle::CLASS => [],
    \Sylius\Bundle\SettingsBundle\SyliusSettingsBundle::CLASS => [],
    \Doctrine\Bundle\DoctrineBundle\DoctrineBundle::CLASS => [],
    \Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::CLASS => [],
    \FOS\RestBundle\FOSRestBundle::CLASS => [],
    \JMS\SerializerBundle\JMSSerializerBundle::CLASS => [],
    \LazerBall\HitTracker\PubSubBundle\PubSubBundle::CLASS => [],
    \LazerBall\HitTracker\GameBundle\HitTrackerGameBundle::CLASS => [],
    \C33s\StaticPageContentBundle\C33sStaticPageContentBundle::CLASS => [],
    \Nelmio\SecurityBundle\NelmioSecurityBundle::CLASS => [],
    \Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::CLASS => [],
    \Bazinga\Bundle\HateoasBundle\BazingaHateoasBundle::CLASS => [],
    \Dunglas\DoctrineJsonOdm\Bundle\DunglasDoctrineJsonOdmBundle::CLASS => [],
    \Incenteev\HashedAssetBundle\IncenteevHashedAssetBundle::CLASS => [],
    \Symfony\Bundle\DebugBundle\DebugBundle::CLASS => ['development' => true, 'test' => true],
    \Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::CLASS => ['development' => true, 'test' => true],
];
