nelmio_csp_reporter:
    path: /csp/report
    defaults:
        _controller: "nelmio_security.csp_reporter_controller:indexAction"
    methods:  [POST]
hittracker_game:
    resource: "@HitTrackerGameBundle/Resources/config/routing.yaml"

hittracker_game_settings:
    path: /settings/games
    defaults:
        _controller: "sylius.controller.settings:updateAction"
        template: "Settings/update.html.twig"
        schema: game

hittracker_site_settings:
    path: /settings/site
    defaults:
        _controller: "sylius.controller.settings:updateAction"
        template: "Settings/update.html.twig"
        schema: site

page:
    path:  /pages/{name}
    defaults:
        _controller: "LazerBall\\HitTracker\\Controller\\StaticPageController::showAction"
home:
    path: /
    defaults:
        _controller: "LazerBall\\HitTracker\\Controller\\StaticPageController::showAction"
        name: help
