nelmio_csp_reporter:
    path: /csp/report
    defaults:
        _controller: "nelmio_security.csp_reporter_controller:indexAction"
    methods:  [POST]
hittracker_game:
    resource: "@HitTrackerGameBundle/Resources/config/routing.yml"

hittracker_game_settings:
    path: /settings/games
    defaults:
        _controller: "sylius.controller.settings:updateAction"
        template: "@Common/Settings/update.html.twig"
        schema: game

hittracker_site_settings:
    path: /settings/site
    defaults:
        _controller: "sylius.controller.settings:updateAction"
        template: "@Common/Settings/update.html.twig"
        schema: site

page:
    path:  /pages/{name}
    defaults:
        _controller: "C33sStaticPageContentBundle:BaseStaticPage:show"
home:
    path: /
    defaults:
        _controller: "C33sStaticPageContentBundle:BaseStaticPage:show"
        name: help
