services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        public: false

    Twig\Extensions\IntlExtension: ~

    # CSRF link extension
    LazerBall\HitTracker\EventListener\CsrfListener:
        arguments:
            $csrfTokenId: "%csrf_link_token_id%"

    LazerBall\HitTracker\FileUploader:
        arguments:
            - "%upload_dir%"
            - "%upload_uri_base_prefix%"

    LazerBall\HitTracker\Twig\:
        resource: '../src/Twig/*'

    # CSRF link extension
    LazerBall\HitTracker\Twig\LinkAttributesExtension:
        arguments:
            $csrfTokenId: "%csrf_link_token_id%"

