services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        public: false

    LazerBall\HitTracker\:
        resource: '../src/*'
        exclude: '../src/{Model,Repository,Tests,GameBundle,Controller}'

    LazerBall\HitTracker\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    LazerBall\HitTracker\GameBundle\Controller\:
        resource: '../src/GameBundle/Controller'
        autowire: false
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: false


    # CSRF link extension
    LazerBall\HitTracker\EventListener\CsrfListener:
        arguments:
            $csrfTokenId: 'link'

    LazerBall\HitTracker\FileUploader:
        arguments:
            - "%upload_dir%"
            - "%upload_uri_base_prefix%"


    # CSRF link extension
    LazerBall\HitTracker\Twig\LinkAttributesExtension:
        arguments:
            $csrfTokenId: 'link'
