parameters:
    database_host: 127.0.0.1
    database_port: ~
    database_name: ht
    database_user: postgres
    database_password: ~
    database_server_version: 9.6

    pubsub_nginx_push_stream_url: "http://localhost/publish/game"
