parameters:
    pubsub_nginx_push_stream_url: "https://ht.local.dev/publish/game"
    livereload_http_url: "https://ht.local.dev/livereload.js?port=443"
    livereload_ws_url: "wss://ht.local.dev"

    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: ~
    database_name: ht
    database_user: postgres
    database_password: ~
    database_server_version: 9.6

